x-tool-conf: &tool-conf
  tty: true
  volumes:
    - ./:/src
  working_dir: /src

services:
  mockery:
    image: vektra/mockery:3.6
    <<: *tool-conf

  lint:
    image: golangci/golangci-lint:v2.7-alpine
    <<: *tool-conf
    command: ./scripts/lint.sh

