name: 'Commit'

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  PGX_DRIVER: './drivers/pgx/'
  
jobs:
  build:
    if: github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: 'Build package'
        run: go build ./

      - name: 'Build pgx driver'
        run: go build ${{ env.PGX_DRIVER }}

  prelint:
    if: github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Detect modules'
        id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  lint:
    needs: prelint

    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        modules: ${{ fromJSON(needs.prelint.outputs.modules) }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Run linters'
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=2m

  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: 'Test'
        run: ./scripts/test.sh
